### ISSUE TITLE
Spot shouldn't stand before stand is called

### ISSUE THREAD

**Issue by skpawar1305** [bdaiinstitute/spot_ros2#175]
for now the behavior is, if we publish to cmd_vel, spot simply stands and walks, when it's in sit mode, should we add a flag for the same?

**Comment by bhung-bdai** [comment]
> for now the behavior is, if we publish to cmd_vel, spot simply stands and walks, when it's in sit mode, should we add a flag for the same?

Hi,

If you command a velocity without the robot standing up, it won't be able to accomplish the movement. That's why it stands up. Do you mean putting a check to make sure the robot is standing before executing, and cancelling if the robot isn't standing? It wasn't designed with that intent.

**Comment by skpawar1305** [comment]
> > for now the behavior is, if we publish to cmd_vel, spot simply stands and walks, when it's in sit mode, should we add a flag for the same?
> 
> Hi,
> 
> If you command a velocity without the robot standing up, it won't be able to accomplish the movement. That's why it stands up. Do you mean putting a check to make sure the robot is standing before executing, and cancelling if the robot isn't standing? It wasn't designed with that intent.

In spot app, it doesn't move till we make it stand first, I believe this is necessary for safety, but if you believe that it wasn't intended, then you may close this issue

**Comment by bhung-bdai** [comment]
That was not the intended design behaviour I believe, but we will add it to our future documentation. Thanks for the heads up

**Comment by skpawar1305** [comment]
This thing is important, another thought?
