### ISSUE TITLE
Robot state publisher should query spot for urdf

### ISSUE THREAD

**Issue by jbarry-bdai** [bdaiinstitute/spot_ros2#21]
Spot's own URDF (which mostly importantly will include the arm if spot has one) can be obtained with:
```
python3 -m bosdyn.client 192.168.80.3 --username <your-username> --password <your-password> state model
```
We should write a wrapper around robot state publisher that grabs the correct urdf off spot rather than using the one in `spot_description`.

**Comment by heuristicus** [comment]
The code in the driver that actually retrieves this appears to be https://github.com/boston-dynamics/spot-sdk/blob/208c885d99813d02b4d78940289cf1c9d0279674/python/bosdyn-client/src/bosdyn/client/command_line.py#L1099-L1170

**Comment by jbarry-bdai** [comment]
@kaiyu-zheng can this be closed?

**Comment by kaiyu-zheng** [comment]
If we're happy with the current `has_arm` solution, then yes!

**Comment by jbarry-bdai** [comment]
Eh I'll leave it open because I think in theory the URDFs could be different per spot based on calibration (not sure if that's true - should verify) so it probably would be better to get each Spot's own URDF.  But this much improves the situation!
