### ISSUE TITLE
Velodyne-VLP 16 pointcloud not being displayed in ROS 2 | Spot Robot

### ISSUE THREAD

**Issue by TheNameisTamil** [bdaiinstitute/spot_ros2#214]
We have configured the VLP-16 on spot robot. We have a linux box with ubuntu 22 and ROS2 humble in it . We tried to bring up the tops of SPOT robot in ros2 . Velodyne point cloud data is timing out. **"Velodyne - poll timeout error".** We have rechecked the ip across the payload and the velodyne but are hitting dead ends. We also changed the launch file code of ROS and updated the same in ROS2 as below.  Need some assistance in bringing up the VLP-16 for spot robot on ROS2. 

launch file: 
from launch import LaunchDescription
from launch_ros.actions import Node
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration

def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument('spot_velodyne', default_value='0', description='Enable Velodyne'),
        DeclareLaunchArgument('autolaunch', default_value='1', description='Auto launch Velodyne'),

        IncludeLaunchDescription(
            condition=IfCondition(LaunchConfiguration('spot_velodyne') == '1' and LaunchConfiguration('autolaunch') == '1'),
            launch_description_source=PythonLaunchDescriptionSource(
                "path/to/[VLP16_points.launch.py](http://vlp16_points.launch.py/)"  # Adjust the path accordingly
            ),
        ),

        # Other nodes and configurations can be added here
    ])

**Comment by khughes-bdai** [comment]
Hi there -- realize this issue has been up for a while, but this seems like more of an issue with the Velodyne rather than `spot_ros2`. I'd recommend trying to first launch the Velodyne launchfiles independently on your Linux box to try to isolate the problem, and if it still isn't working, reaching out to Velodyne support and/or leaving an issue on their repository: https://github.com/ros-drivers/velodyne
