### ISSUE TITLE
Sit/stand status is not updated after publishing to /cmd_vel

### ISSUE THREAD

**Issue by JacobJBeck** [bdaiinstitute/spot_ros2#260]
The message type `spot_msgs/msg/Feedback.msg` published on `/status/feedback` includes booleans for `sitting` and `standing`. These values update correctly when the state is changed via calls to the `/stand` and `/sit` services, however they do not change when a message published to `/cmd_vel` causes a sitting Spot to stand.

**Comment by khughes-bdai** [comment]
Should be resolved with https://github.com/bdaiinstitute/spot_wrapper/pull/130!
