### ISSUE TITLE
Protobuff to ros2 message conversion has some functions that are called but undefined.

### ISSUE THREAD

**Issue by myeatman-bdai** [bdaiinstitute/spot_ros2#30]
In spot_driver->spot_driver->conversions.py, the function "convert_proto_to_bosdyn_msgs_stand_command_request" is called but is not defined. There are several other instances of this through the file for various names: 'convert_proto_to_bosdyn_msgs_sit_command_request', etc... .

**Comment by amessing-bdai** [comment]
Fixed in #35
