### ISSUE TITLE
Issue with odom frame becoming child of body in tf

### ISSUE THREAD

**Issue by Rodhaaret** [bdaiinstitute/spot_ros2#302]
Hey everyone

We just updated the Spot SDK to 4.0.0 and the same with the Spot_ros2 wrapper and are currently trying to get our software up and running correctly again. However we are seeing some issue with the /tf caused by the odometry. 

When looking at the tf tree we see that the odom becomes a child of the body frame, which we assume is the issue, since this was an issue from a previous post: #62 . I assume that the problem occurs when the state_publisher was converted to C++ but not completely sure where to look.

We noticed that the spot_driver gives the following error msg when running the code that previously worked: 
[component_container_mt-7] [ERROR] [1710771142.051852545] [register_node_back]: TF2 exception:
[component_container_mt-7] The tf tree is invalid because it contains a loop.
[component_container_mt-7] Frame base_link exists with parent body.
[component_container_mt-7] Frame body exists with parent odom.
[component_container_mt-7] Frame front_rail exists with parent body.
[component_container_mt-7] Frame rear_rail exists with parent body.
[component_container_mt-7] Frame back exists with parent head.
[component_container_mt-7] Frame head exists with parent body.
[component_container_mt-7] Frame back_fisheye exists with parent back.
[component_container_mt-7] Frame frontleft exists with parent head.
[component_container_mt-7] Frame frontleft_fisheye exists with parent frontleft.
[component_container_mt-7] Frame frontright_fisheye exists with parent frontright.
[component_container_mt-7] Frame frontright exists with parent head.
[component_container_mt-7] Frame left exists with parent head.
[component_container_mt-7] Frame left_fisheye exists with parent left.
[component_container_mt-7] Frame right exists with parent head.
[component_container_mt-7] Frame right_fisheye exists with parent right.
[component_container_mt-7] Frame flat_body exists with parent body.
[component_container_mt-7] Frame odom exists with parent map.
[component_container_mt-7] Frame gpe exists with parent odom.
[component_container_mt-7] Frame vision exists with parent body.
[component_container_mt-7] Frame front_left_hip exists with parent body.
[component_container_mt-7] Frame front_left_upper_leg exists with parent front_left_hip.
[component_container_mt-7] Frame front_left_lower_leg exists with parent front_left_upper_leg.
[component_container_mt-7] Frame front_right_hip exists with parent body.
[component_container_mt-7] Frame front_right_upper_leg exists with parent front_right_hip.
[component_container_mt-7] Frame front_right_lower_leg exists with parent front_right_upper_leg.
[component_container_mt-7] Frame rear_left_hip exists with parent body.
[component_container_mt-7] Frame rear_left_upper_leg exists with parent rear_left_hip.
[component_container_mt-7] Frame rear_left_lower_leg exists with parent rear_left_upper_leg.
[component_container_mt-7] Frame rear_right_hip exists with parent body.
[component_container_mt-7] Frame rear_right_upper_leg exists with parent rear_right_hip.
[component_container_mt-7] Frame rear_right_lower_leg exists with parent rear_right_upper_leg.
[component_container_mt-7] Frame fiducial_14 exists with parent odom.
[component_container_mt-7] Frame filtered_fiducial_14 exists with parent odom.

Here is how the tf looks like running the spot_driver 
[frames_2024-03-18_13.43.41.pdf](https://github.com/bdaiinstitute/spot_ros2/files/14636386/frames_2024-03-18_13.43.41.pdf)
![image](https://github.com/bdaiinstitute/spot_ros2/assets/55698481/8f231b9b-eb34-4d61-8d0d-16d74a49ddd5)

**Comment by Rodhaaret** [comment]
Upon further investigation the issue is coming from robot_state.cpp or at least hard coding that if parent_frame is body and child_frame is odom it should swap them fixes our issue

**From line 115-144 we modified the file to the following to see what was going on:**
for (const auto& [frame_id, transform] :
       robot_state.kinematic_state().transforms_snapshot().child_to_parent_edge_map()) {
    // Do not publish frames without parents
    if (transform.parent_frame_name().empty()) {
      continue;
    }
    auto parent_frame_name = transform.parent_frame_name().find('/') == std::string::npos
                                       ? prefix + transform.parent_frame_name()
                                       : transform.parent_frame_name();
    auto frame_name = frame_id.find('/') == std::string::npos ? prefix + frame_id : frame_id;

    if(parent_frame_name =="body" && frame_name=="odom"){
      parent_frame_name ="odom";
      frame_name="body";
    }

    //std::cout<<std::endl<<"parent_frame_name: "<<parent_frame_name<<std::endl;
    //std::cout<<std::endl<<"frame_name: "<<frame_name<<std::endl;

    // set target frame(preferred odom frame) as the root node in tf tree
    if (preferred_base_frame_id == frame_name) {
      tf_msg.transforms.push_back(
          toTransformStamped(~(transform.parent_tform_child()), frame_name, parent_frame_name, local_time));
    } else {
      tf_msg.transforms.push_back(
          toTransformStamped(transform.parent_tform_child(), parent_frame_name, frame_name, local_time));
    }
  }
  
  Running the spot_driver now sets the odom correctly and our code now works. However im unsure what a permanent fix could be.

**Comment by khughes-bdai** [comment]
Should be resolved with https://github.com/bdaiinstitute/spot_ros2/pull/304 !
