### ISSUE TITLE
Releases or tags aligning with Spot SDK releases

### ISSUE THREAD

**Issue by GregoryLeMasurier** [bdaiinstitute/spot_ros2#334]
It would be really convenient if we had some way to quickly switch to versions of spot_ros2 that are compatible with each spot sdk version. Currently, the best way seems to be going through each commit looking at the version listed in the README.

This would be really helpful for reproducing older work, or for people who start developing for a robot which isn't running the latest sdk (sometimes we hold off on upgrading due to particular bugs or if a project needs to be held to a particular version).

**Comment by khughes-bdai** [comment]
Added tags corresponding to the latest versions of `spot_ros2` that support `spot-sdk` `3.3.0` and `3.3.2`. Let me know if this works!
https://github.com/bdaiinstitute/spot_ros2/tags
