### ISSUE TITLE
Core I/O data

### ISSUE THREAD

**Issue by annanya-tamu** [bdaiinstitute/spot_ros2#354]
Hello,

I recently attached the Core I/O to spot and wanted to access the Lidar data, but when I run `ros2 topic list -t | grep 'sensor_msgs/msg/LaserScan'`, I don't see any topics listed. Is there something that I'm missing?

Thanks!

**Comment by bhung-bdai** [comment]
We don't currently support the Core I/O attachments including publishing LaserScan messages @annanya-tamu. We can look into it, or you can feel free to make a PR updating the driver to check and account for it.
