### ISSUE TITLE
IMU position and orientation in URDF

### ISSUE THREAD

**Issue by kevinzakka** [bdaiinstitute/spot_ros2#395]
Hello,

I'm working on adding Spot to [MuJoCo Menagerie](https://github.com/google-deepmind/mujoco_menagerie) and was wondering if you knew the pose of the IMU relative to the body link? Would be helpful for adding sensors at the IMU site.

**Comment by khughes-bdai** [comment]
Hello, 
I think this information should be available via the [`ImuState`](https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference.html#imustate), which seems to be used in the [`RobotStateStreamResponse`](https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference.html#robotstatestreamresponse) message.  We don't currently support this kind of low level joint streaming in `spot_ros2`, but you should be able to call this via direct Spot SDK calls. I'd recommend reaching out to Boston Dynamics support as well as they might have a more clear answer.
