### ISSUE TITLE
Change SSH submodule links to HTTPS

### ISSUE THREAD

**Issue by ryan-roche** [bdaiinstitute/spot_ros2#412]
I'm trying to automate the process of installing the driver within a Dockerfile, but I'm running into an issue with the submodule links. They're SSH links, and it fails to initialize & download the submodules due to not having an SSH key configured.

I was able to run a `sed` command within the Dockerfile to replace the GitHub SSH links with their HTTPS equivalents to anonymously download the submodules (they are public repositories, after all), but would it be possible to replace the links in the actual repo with HTTPS ones?

**Comment by tcappellari-bdai** [comment]
I believe they are already HTTPS? I'm not sure why your environment would want to SSH

https://github.com/bdaiinstitute/spot_ros2/blob/be4b5e0bb892c287cb38b98eadbb37d9b1fe2e12/.gitmodules#L1-L6

**Comment by ryan-roche** [comment]
Strange... I must have been mistaken.
