### ISSUE TITLE
Hanging on message generation

### ISSUE THREAD

**Issue by marlow-fawn** [bdaiinstitute/spot_ros2#440]
Having an issue when running on bosdyn_api_msgs. It appears to hang on the following message:

[NetworkComputeResponse.txt](https://github.com/user-attachments/files/16415886/NetworkComputeResponse.txt)

I don't actually need this message, so if there's some way to ignore certain messages in a package that would be a sufficient workaround for now.

**Comment by khughes-bdai** [comment]
Hi @marlow-fawn 
Just to clarify, what is hanging here? Is it when you try to import `bosdyn_api_msgs`?

**Comment by marlow-fawn** [comment]
I ended up posting this to the wrong repo, please feel free to delete!
