### ISSUE TITLE
Can't find documentation

### ISSUE THREAD

**Issue by Mizo330** [bdaiinstitute/spot_ros2#479]
Hi!

I've had issues with figuring out how to set the arm to drag mode, and took me a few days to figure out that velocity_command is a service request, not an action goal (as all commands made with the RobotCommandBuilder class can be sent as an action, except this.).
I couldn't find any documentation to use these commands properly, is there any documentation for the code?

**Comment by tcappellari-bdai** [comment]
Unfortunately, we are still working on the documentation. Thank you for your patience!
