### ISSUE TITLE
Images not obtained for publishing

### ISSUE THREAD

**Issue by gial11** [bdaiinstitute/spot_ros2#50]
Hello, few seconds after having successfully launched the driver I repeatedly receive the following error:<p></p>
`[spot_ros2-1] The following exception was never retrieved: 'NoneType' object has no attribute 'frontleft'`.<p></p>
It seems that the images are not correctly obtained in the functions responsible of publishing them like [this](https://github.com/bdaiinstitute/spot_ros2/blob/00bee893d42ab84e09423f5aa401e2162b328278/spot_driver/spot_driver/spot_ros2.py#L210) one.

**Comment by skpawar1305** [comment]
https://github.com/bdaiinstitute/spot_ros2/issues/64#issuecomment-1563285185

**Comment by gial11** [comment]
Solved by doing [this](https://github.com/bdaiinstitute/spot_ros2/issues/64#issuecomment-1563285185). Thank you.
