### ISSUE TITLE
offering incompatible QoS when when visualizing pointcloud in rviz2

### ISSUE THREAD

**Issue by JiaheXu** [bdaiinstitute/spot_ros2#509]
Hi BDAI,

When I try to visualize the point cloud from depth cameras, the spot driver terminal shows `New publisher discovered on topic '/depth_registered/back/points', offering incompatible QoS. No messages will be sent to it. Last incompatible policy: RELIABILITY_QOS_POLICY`. I can see grayscale images and dept-map and pointcloud topics. Please help me fix this.

Best,
Jiahe

**Comment by khughes-bdai** [comment]
You will have to change the QOS policy through the rviz drop down on this topic to "Best Effort": 

![image](https://github.com/user-attachments/assets/61c30a6f-d1f5-433d-8437-5db9f6711b97)

**Comment by tcappellari-bdai** [comment]
Are you using rviz for visualization? You should be able to edit the QoS directly in it to match
