### ISSUE TITLE
How to integrate the ros2 driver in Isaacsim env

### ISSUE THREAD

**Issue by JiaheXu** [bdaiinstitute/spot_ros2#515]
Hi BDAI,

I am working on integrating the Spot(with a gripper) into the Isaacsim env, I need to use this ros2 driver to give high-level commands to the spot. Is there any code I can use for the integration?

Best,
Jiahe Xu

**Comment by khughes-bdai** [comment]
Hi @JiaheXu ,
Unfortunately, this repo does not support any integration with Isaac Sim.
