### ISSUE TITLE
Using this repo for simulation

### ISSUE THREAD

**Issue by AayushManShrestha** [bdaiinstitute/spot_ros2#532]
My goal is to control Spot robot using Python in a simulated environment (Gazebo, Unity). I would like to send commands from a Python program (e.g., to make Spot walk), and have the robot perform these actions within the simulation.

Could you please guide me on how to use this repository to achieve this functionality?

**Comment by khughes-bdai** [comment]
Hi @AayushManShrestha ,
Unfortunately, this repo does not currently have support for running in a simulated environment. If you are interested in joint level commands using the low level interface, [this repo](https://github.com/boston-dynamics/spot-rl-example) could be useful. There is also [this repository](https://github.com/MASKOR/webots_ros2_spot) which provides some high level commands to move the robot in sim. [This discussion post](https://github.com/bdaiinstitute/spot_ros2/discussions/109) might also be helpful.
