### ISSUE TITLE
Remove humble branch

### ISSUE THREAD

**Issue by mjforan** [bdaiinstitute/spot_ros2#59]
Since main supports ROS 2 Humble it is unnecessary to have a separate humble branch. I suspect many of the branches are extraneous at this point, but the humble one is especially confusing because ROS packages often have branches for each distribution.

**Comment by khughes-bdai** [comment]
Realize that this was posted almost a year ago, but it's a good point! @METEORITENMAX it looks like this branch is yours -- is it okay to delete it?
